import { readFile } from 'node:fs/promises'
import type {
  AiUsageDetection,
  ClassifiedFile,
  ComplianceResult,
  SystemDeclaration,
} from '../../types.js'

const AI_DISCLOSURE_PATTERNS = [
  'ai-disclosure',
  'ai_disclosure',
  'aiDisclosure',
  'powered by ai',
  'powered by artificial intelligence',
  'ai-generated',
  'ai_generated',
  'aiGenerated',
  'generated by ai',
  'this is an ai',
  'interacting with an ai',
  'automated system',
  'chatbot',
  'virtual assistant',
  'c2pa',
  'content-credentials',
  'synthid',
]

async function hasAiDisclosureInCode(
  allFiles: ClassifiedFile[],
): Promise<{ found: boolean; filePaths: string[] }> {
  const relevantFiles = allFiles.filter(
    (f) =>
      f.language === 'typescript' ||
      f.language === 'javascript' ||
      f.language === 'python',
  )

  const matchedPaths: string[] = []

  for (const file of relevantFiles) {
    try {
      const content = await readFile(file.path, 'utf-8')
      const lowerContent = content.toLowerCase()

      const hasDisclosure = AI_DISCLOSURE_PATTERNS.some((pattern) =>
        lowerContent.includes(pattern),
      )

      if (hasDisclosure) {
        matchedPaths.push(file.path)
      }
    } catch {
      continue
    }
  }

  return {
    found: matchedPaths.length > 0,
    filePaths: matchedPaths,
  }
}

export async function checkArt50Transparency(
  _system: SystemDeclaration,
  _detections: AiUsageDetection[],
  allFiles: ClassifiedFile[],
): Promise<ComplianceResult[]> {
  const results: ComplianceResult[] = []

  const disclosure = await hasAiDisclosureInCode(allFiles)

  if (disclosure.found) {
    results.push({
      articleId: 'art50',
      status: 'pass',
      title: 'AI interaction disclosure detected',
      detail: 'AI disclosure patterns found in user-facing code. Article 50 requires that AI systems interacting with natural persons disclose they are AI.',
      filePaths: disclosure.filePaths,
      referenceUrl: 'https://artificialintelligenceact.eu/article/50/',
      phase: 1,
    })
  } else {
    results.push({
      articleId: 'art50',
      status: 'warning',
      title: 'No AI interaction disclosure detected',
      detail: 'No AI disclosure patterns found in code. If this system interacts directly with natural persons, Article 50 requires clear disclosure that the user is interacting with an AI system. This must be provided at the latest at the time of first interaction.',
      referenceUrl: 'https://artificialintelligenceact.eu/article/50/',
      phase: 1,
    })
  }

  return results
}
