import * as core from '@actions/core'
import * as github from '@actions/github'
import {
  scan,
  formatGitHubPRComment,
  formatJsonReport,
  formatSarifReport,
  loadBaseline,
  computeDiff,
  generateBadgeSvg,
  generateBadgeUrl,
} from '@systima/comply'
import type { FailOn, OutputFormat, ScanResult } from '@systima/comply'
import { resolve } from 'node:path'
import { writeFile, mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'

function shouldFail(result: ScanResult, failOn: FailOn): boolean {
  if (failOn === 'none') return false
  const severity = result.summary.findingsBySeverity
  switch (failOn) {
    case 'critical': return severity.critical > 0
    case 'fail': return severity.critical > 0 || severity.fail > 0
    case 'warning': return severity.critical > 0 || severity.fail > 0 || severity.warning > 0
    default: return false
  }
}

function buildJobSummary(result: ScanResult): string {
  const { summary } = result
  const score = Math.round(summary.overallComplianceScore * 100)
  const statusEmoji = summary.findingsBySeverity.critical > 0
    ? '🔴'
    : summary.findingsBySeverity.fail > 0
      ? '🟠'
      : summary.findingsBySeverity.warning > 0
        ? '🟡'
        : '🟢'

  const lines: string[] = [
    `## ${statusEmoji} EU AI Act Compliance: ${score}%`,
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Systems scanned | ${summary.totalSystems} |`,
    `| AI detections | ${summary.totalDetections} |`,
    `| Critical findings | ${summary.findingsBySeverity.critical} |`,
    `| Failed checks | ${summary.findingsBySeverity.fail} |`,
    `| Warnings | ${summary.findingsBySeverity.warning} |`,
    `| Risk level | ${summary.highestRiskLevel} |`,
    '',
  ]

  for (const system of result.systems) {
    const sysScore = Math.round(system.complianceScore * 100)
    const passed = system.complianceResults.filter((r) => r.status === 'pass').length
    const total = system.complianceResults.filter((r) => r.status !== 'skipped').length
    lines.push(`**${system.systemName}** (${system.classification.riskLevel}): ${sysScore}% — ${passed}/${total} obligations met`)
  }

  lines.push('')
  lines.push('*Generated by [Systima Comply](https://github.com/systima-ai/comply)*')

  return lines.join('\n')
}

async function run(): Promise<void> {
  try {
    const configPath = core.getInput('config-path') || '.systima.yml'
    const scanMode = core.getInput('scan-mode') || 'diff'
    const failOn = (core.getInput('fail-on') || 'critical') as FailOn
    const outputFormat = (core.getInput('output-format') || 'comment') as OutputFormat | 'all'
    const baselinePath = core.getInput('baseline-path') || '.systima-baseline.json'
    const badgePath = core.getInput('badge-path') || ''

    const workspace = process.env['GITHUB_WORKSPACE'] ?? process.cwd()

    core.info('Starting Systima Comply EU AI Act compliance scan...')

    const result = await scan({
      path: workspace,
      configPath: resolve(workspace, configPath),
      scanMode: scanMode === 'diff' ? 'diff' : 'full',
      outputFormat: outputFormat === 'all' ? 'json' : outputFormat,
      failOn,
      verbose: false,
    })

    const baseline = await loadBaseline(resolve(workspace, baselinePath))
    const diff = baseline ? computeDiff(baseline, result) : undefined

    core.setOutput('compliance-score', result.summary.overallComplianceScore.toString())
    core.setOutput('risk-level', result.summary.highestRiskLevel)
    core.setOutput('findings-count', result.summary.totalFindings.toString())
    core.setOutput('classification-changed', result.summary.classificationChanged.toString())
    core.setOutput('badge-url', generateBadgeUrl(result))

    await core.summary.addRaw(buildJobSummary(result)).write()
    core.info('Job summary written')

    if (outputFormat === 'comment' || outputFormat === 'all') {
      const comment = formatGitHubPRComment(result, diff)

      const token = process.env['GITHUB_TOKEN']
      if (token && github.context.payload.pull_request) {
        const octokit = github.getOctokit(token)
        const prNumber = github.context.payload.pull_request.number

        const { data: existingComments } = await octokit.rest.issues.listComments({
          ...github.context.repo,
          issue_number: prNumber,
        })

        const botComment = existingComments.find(
          (c) => c.body?.includes('Systima Comply'),
        )

        if (botComment) {
          await octokit.rest.issues.updateComment({
            ...github.context.repo,
            comment_id: botComment.id,
            body: comment,
          })
        } else {
          await octokit.rest.issues.createComment({
            ...github.context.repo,
            issue_number: prNumber,
            body: comment,
          })
        }

        core.info('PR comment posted successfully')
      }
    }

    if (outputFormat === 'json' || outputFormat === 'all') {
      const json = formatJsonReport(result, diff)
      await writeFile(resolve(workspace, 'comply-results.json'), json, 'utf-8')
      core.info('JSON report written to comply-results.json')
    }

    if (outputFormat === 'sarif' || outputFormat === 'all') {
      const sarif = formatSarifReport(result)
      await writeFile(resolve(workspace, 'comply-results.sarif'), sarif, 'utf-8')
      core.info('SARIF report written to comply-results.sarif')
    }

    if (badgePath) {
      const badgeFullPath = resolve(workspace, badgePath)
      await mkdir(dirname(badgeFullPath), { recursive: true })
      const svg = generateBadgeSvg(result)
      await writeFile(badgeFullPath, svg, 'utf-8')
      core.info(`Badge SVG written to ${badgePath}`)
    }

    if (shouldFail(result, failOn)) {
      core.setFailed(
        `Compliance check failed: ${result.summary.findingsBySeverity.critical} critical, ${result.summary.findingsBySeverity.fail} failures, ${result.summary.findingsBySeverity.warning} warnings`,
      )
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    core.setFailed(`Systima Comply failed: ${message}`)
  }
}

run()
