import type { ScanResult, ComplianceDiff } from '../types.js'

export function formatMarkdownReport(
  result: ScanResult,
  diff?: ComplianceDiff,
): string {
  const { summary } = result
  const lines: string[] = []

  lines.push('# EU AI Act Compliance Report')
  lines.push('')
  lines.push(`**Generated**: ${result.timestamp}`)
  lines.push(`**Scan path**: ${result.scanPath}`)
  lines.push(`**Scan mode**: ${result.scanMode}`)
  lines.push('')

  lines.push('## Summary')
  lines.push('')
  lines.push(`| Metric | Value |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Systems scanned | ${summary.totalSystems} |`)
  lines.push(`| Total detections | ${summary.totalDetections} |`)
  lines.push(`| Total findings | ${summary.totalFindings} |`)
  lines.push(`| Critical findings | ${summary.findingsBySeverity.critical} |`)
  lines.push(`| Failed checks | ${summary.findingsBySeverity.fail} |`)
  lines.push(`| Warnings | ${summary.findingsBySeverity.warning} |`)
  lines.push(`| Overall compliance score | ${(summary.overallComplianceScore * 100).toFixed(1)}% |`)
  lines.push(`| Highest risk level | ${summary.highestRiskLevel} |`)
  lines.push('')

  for (const system of result.systems) {
    lines.push(`## ${system.systemName} (${system.classification.riskLevel}-risk)`)
    lines.push('')

    if (system.classification.annexIiiCategory) {
      lines.push(`**Annex III Category**: ${system.classification.annexIiiCategory}`)
    }
    if (system.classification.rationale) {
      lines.push(`**Rationale**: ${system.classification.rationale}`)
    }
    lines.push(`**Compliance score**: ${(system.complianceScore * 100).toFixed(1)}%`)
    lines.push('')

    if (system.detections.length > 0) {
      lines.push('### Detected AI Frameworks')
      lines.push('')
      lines.push('| Framework | Type | File | Line |')
      lines.push('|-----------|------|------|------|')
      for (const detection of system.detections) {
        lines.push(
          `| ${detection.frameworkName} | ${detection.detectionType} | ${detection.filePath} | ${detection.lineNumber} |`,
        )
      }
      lines.push('')
    }

    if (system.classificationMismatches.length > 0) {
      lines.push('### Classification Mismatches')
      lines.push('')
      for (const mismatch of system.classificationMismatches) {
        lines.push(
          `- **${mismatch.declaredRiskLevel} → ${mismatch.suggestedRiskLevel}**: ${mismatch.reason}`,
        )
      }
      lines.push('')
    }

    if (system.complianceResults.length > 0) {
      lines.push('### Obligation Compliance')
      lines.push('')
      lines.push('| Article | Obligation | Status | Detail |')
      lines.push('|---------|-----------|--------|--------|')
      for (const cr of system.complianceResults) {
        const statusLabel = cr.status.charAt(0).toUpperCase() + cr.status.slice(1)
        lines.push(
          `| ${cr.articleId.replace('art', 'Art. ')} | ${cr.title} | ${statusLabel} | ${cr.detail} |`,
        )
      }
      lines.push('')
    }
  }

  if (result.undeclaredSystems.length > 0) {
    lines.push('## Undeclared AI Systems')
    lines.push('')
    for (const undeclared of result.undeclaredSystems) {
      lines.push(`- ${undeclared.reason}`)
    }
    lines.push('')
  }

  if (diff) {
    lines.push('## Changes Since Baseline')
    lines.push('')
    lines.push(`| Metric | Value |`)
    lines.push(`|--------|-------|`)
    lines.push(`| New findings | ${diff.newFindings.length} |`)
    lines.push(`| Resolved findings | ${diff.resolvedFindings.length} |`)
    lines.push(`| Classification changes | ${diff.classificationChanges.length} |`)
    lines.push(`| Compliance score delta | ${(diff.complianceScoreDelta * 100).toFixed(1)}% |`)
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('*Generated by [Systima Comply](https://github.com/systima-ai/comply). This is an engineering tool, not legal advice.*')

  return lines.join('\n')
}
